# $OpenBSD$

COMMENT=		compile mdoc macros into mark-up languages

DISTNAME=		mdocml-@VERSION@
CATEGORIES=		devel

HOMEPAGE=		http://mdocml.bsd.lv/

MAINTAINER=		Kristaps Dzonsons <kristaps@kth.se>

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		http://sysjail.bsd.lv/dist/

WANTLIB=		c

NO_REGRESS=		Yes

.include <bsd.port.mk>
