# $OpenBSD$

COMMENT=		mdoc macro compiler

DISTNAME=		mdocml-@VERSION@
CATEGORIES=		textproc

HOMEPAGE=		http://mdocml.bsd.lv/

MAINTAINER=		Kristaps Dzonsons <kristaps@kth.se>

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		http://mdocml.bsd.lv/snapshots/

WANTLIB=		c

.include <bsd.port.mk>
