.\" $Id$
.\"
.\" Copyright (c) 2009 Kristaps Dzonsons <kristaps@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the
.\" above copyright notice and this permission notice appear in all
.\" copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
.\" PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt mandoc 1
.Os
.\" SECTION
.Sh NAME
.Nm mandoc
.Nd format and display BSD manuals
.\" SECTION
.Sh SYNOPSIS
.Nm mandoc
.Op Fl V
.Op Fl f Ns Ar option...
.Op Fl W Ns Ar err...
.Op Fl T Ns Ar output
.Op Ar infile...
.\" SECTION
.Sh DESCRIPTION
The
.Nm
utility formats a BSD 
.Dq mdoc 
manual page for display.  The arguments are as follows:
.Bl -tag -width XXXXXXXXXXXX
.\" ITEM
.It Fl f Ns Ar option...
Override default compiler behaviour.  See 
.Sx Compiler Options
for details.
.\" ITEM
.It Fl T
Output format.  See
.Sx Output Formats
for available formats.  Defaults to
.Fl T Ns Ar ascii .
.\" ITEM
.It Fl V
Print version and exit.
.\" ITEM
.It Fl W Ns Ar err...
Print warning messages.  May be set to 
.Fl W Ns Ar all
for all warnings, 
.Ar compat
for groff/troff-compatibility warnings, or
.Ar syntax
for syntax warnings.  If
.Fl W Ns Ar error 
is specified, warnings are considered errors and cause utility
termination.  Multiple 
.Fl W
arguments may be comma-separated, such as
.Fl W Ns Ar error,all .
.\" ITEM
.It Ar infile...
Read input from zero or more
.Ar infile .
If unspecified, reads from stdin.
.El
.\" PARAGRAPH
.Pp
By default, 
.Nm 
reads from stdin and prints 78-column backspace-encoded output to stdout
as if
.Fl T Ns Ar ascii
were provided.
.\" PARAGRAPH
.Pp
.Ex -std mandoc
.\" SUB-SECTION
.Ss Output Formats
The
.Nm
utility accepts the following
.Fl T
arguments:
.Bl -tag -width XXXXXXXXXXXX -offset XXXX
.It Ar ascii
Produce 7-bit ASCII output, backspace-encoded for bold and underline
styles.  This is the default.
.It Ar tree
Produce an indented parse tree.
.It Ar lint
Parse only: produce no output.
.El
.\" SUB-SECTION
.Ss Compiler Options
Default compiler behaviour may be overriden with the
.Fl f
flag.
.Bl -tag -width XXXXXXXXXXXX -offset XXXX
.It Fl f Ns Ar ign-scope
When rewinding the scope of a block macro, forces the compiler to ignore
scope violations.  This can seriously mangle the resulting tree.
.It Fl f Ns Ar ign-escape
Ignore invalid escape sequences.
.It Fl f Ns Ar ign-macro
Ignore unknown macros at the start of input lines.
.El
.\" PARAGRAPH
.Pp
As with the
.Fl W
flag, multiple
.Fl f
options may be grouped and delimited with a comma.  Using
.Fl f Ns Ar ign-scope,ign-escape ,
for example, will try to ignore scope and character-escape errors.
.\" SECTION
.Sh EXAMPLES
To page this manual page on the terminal:
.\" PARAGRAPH
.Pp
.D1 % mandoc \-Wall,error mandoc.1 2>&1 | less
.\" SECTION
.Sh SEE ALSO
.Xr mdoc 7
.\" 
.Sh AUTHORS
The
.Nm
utility was written by 
.An Kristaps Dzonsons Aq kristaps@openbsd.org .
.\" SECTION
.Sh CAVEATS
The 
.Nm
utility doesn't yet know how to display the following:
.Pp
.Bl -bullet -compact
.It
The \-hang 
.Sq \&Bl
list is not yet supported.
.It
The \-literal and \-unfilled 
.Sq \&Bd
displays only accept text contents.
.It
The
.Sq \&Xo/Xc
pair isn't supported.
.It
The
.Sq \&Sm
macro has no effect, yet.
.El
.Pp
Other macros still aren't supported by virtue of nobody complaining
about their absence.  Please report any omissions: this is a work in
progress.
