.Dd $Mdocdate$
.Dt "Writing Unix Documentation" paper
.Os
.Sh NAME
.Nm Writing Unix Documentation
.Nd a guide to writing Unix manuals
.Sh DESCRIPTION
					<h1>
					Writing Unix Documentation
					</h1>

					<p>
					<span class="attn">A utility without documentation is of no utility at all.</span>
					</p>

					<p>
					A system component's documentation describes the utility of that component, whether it's a device
					driver, an executable or, most importantly, a game.  Although there are plenty of documents available on
					how to <i>read</i> Unix documents, or where to find them, few focus on how to <i>write</i> them.
					</p>

					<p>
					This document serves as a reference guide to writing Unix documentation.  If you add something to your
					operating system, whether it's a new file format or directory structure or device driver, it needs
					documentation.
					</p>
				</td>
			</tr>
			<tr>
				<td>
					<div class="foot">
						Copyright &#169; 2009 Kristaps D&#382;onsons, $Date$
					</div>
				</td>
			</tr>
		</tbody>
	</table>
	</body>
</html>
