.\" $Id$
.\"
.\" Copyright (c) 2009 Kristaps Dzonsons <kristaps@kth.se>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the
.\" above copyright notice and this permission notice appear in all
.\" copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
.\" PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt mdocmterm 1
.Os
.\" SECTION
.Sh NAME
.Nm mdocmterm
.Nd mdoc macro compiler
.\" SECTION
.Sh SYNOPSIS
.Nm mdocmterm
.Op Fl v
.Op Fl W Ns Ar err...
.Op Ar infile
.\" SECTION
.Sh DESCRIPTION
The
.Nm
utility formats a BSD 
.Dq mdoc 
manual page for display on the terminal.  The arguments are as follows:
.Bl -tag -width "\-Werr... "
.\" ITEM
.It Fl v
Print verbose parsing output.
.\" ITEM
.It Fl W Ns Ar err...
Print warning messages.  May be set to 
.Fl W Ns Ar all
for all warnings, 
.Ar compat
for groff/troff-compatibility warnings, or
.Ar syntax
for syntax warnings.  If
.Fl W Ns Ar error 
is specified, warnings are considered errors and cause utility
termination.  Multiple 
.Fl W
arguments may be comma-separated, such as
.Fl W Ns Ar error,all .
.\" ITEM
.It Ar infile
Read input from
.Ar infile ,
which may be 
.Dq \-
for stdin.
.El
.\" PARAGRAPH
.Pp
The
.Nm
utility is a formatting front-end for
.Xr mdoc 3 ,
which parses the 
.Dq mdoc
input, documented at
.Xr mdoc 7
and
.Xr mdoc.samples 7 ,
into an abstract syntax tree.
.\" PARAGRAPH
.Pp
By default,
.Nm
reads from stdin and prints terminal-encoded output to stdout.
.\" PARAGRAPH
.Pp
.Ex -std mdocmterm
.\" PARAGRAPH
.Pp
.Nm
is
.Ud
.\" SUB-SECTION
.Ss Character Escapes
This section documents the character-escapes accepted by
.Xr mdocterm 1 .
Note that the \\x, \\(xx and \\[n] forms are described here; the \\*(xx,
\\*[n] and \\*x forms described in
.Xr mdoc.samples 7
are deprecated, but still rendered.  All one- and two-character
sequences may be used in the n-character sequence \\[n].
.Pp
Note that the
.Em Output
column will render differently whether executed with
.Xr mdocterm 1 
or another output filter.
.\" PARAGRAPH
.Pp
Grammatic:
.Pp
.Bl -tag -width "OutputXXXX" -offset "XXXX" -compact
.It Em Output
.Em Input (Name)
.It \(em
\\(em (em-dash)
.It \(en
\\(en (en-dash)
.It \-
\\- (hyphen)
.It \\
\\ (back-slash)
.El
.\" PARAGRAPH
.Pp
Enclosures:
.Pp
.Bl -tag -width "OutputXXXX" -offset "XXXX" -compact
.It Em Output
.Em Input (Name)
.It \(rB
\\(rB (right bracket)
.It \(lB
\\(rB (left bracket)
.It \(lq
\\(lq (left double-quote)
.It \(rq
\\(rq, \\' (right double-quote)
.It \(oq
\\(lq, \\` (left single-quote)
.It \(aq
\\(aq (right single-quote, apostrophe)
.El
.\" PARAGRAPH
.Pp
Indicatives:
.Pp
.Bl -tag -width "OutputXXXX" -offset "XXXX" -compact
.It Em Output
.Em Input (Name)
.It \(<-
\\(<- (left arrow)
.It \(->
\\(-> (right arrow)
.It \(ua
\\(ua (up arrow)
.It \(da
\\(da (down arrow)
.El
.\" PARAGRAPH
.Pp
Mathematical:
.Pp
.Bl -tag -width "OutputXXXX" -offset "XXXX" -compact
.It Em Output
.Em Input (Name)
.It \(<=
\\(<= (less-than-equal)
.It \(>=
\\(>= (greater-than-equal)
.It \(==
\\(== (greater-than-equal)
.It \(!=
\\(!= (not equal)
.It \(if
\\(if (infinity)
.It \(na
\\(na (NaN)*
.It \(+-
\\(+- (plus-minus)
.It \(**
\\(** (asterisk)
.El
.\" PARAGRAPH
.Pp
Diacritics:
.Pp
.Bl -tag -width "OutputXXXX" -offset "XXXX" -compact
.It Em Output
.Em Input (Name)
.It \(ga
\\(ga (accent grave)
.It \(aa
\\(aa (accent accute)
.El
.\" PARAGRAPH
.Pp
Special symbols:
.Pp
.Bl -tag -width "OutputXXXX" -offset "XXXX" -compact
.It Em Output
.Em Input (Name)
.It \(bu
\\(bu (bullet)
.It \(ba
\\(ba (bar)
.It \(co
\\(co (copyright)
.El 
.Pp
*This is a deviation from the standard, as NaN is usually rendered as
\\*(Na, which is a deprecated form.  We introduce \\(na, which follows
the more general syntax.
.\" SECTION
.Sh EXAMPLES
To display this manual page:
.\" PARAGRAPH
.Pp
.D1 % mdocmterm \-Wall,error mdocmterm.1 
.\" PARAGRAPH
.Pp
To pipe a manual page to the pager:
.Pp
.D1 % mdocterm mdocterm.1 | less -R
.\" SECTION
.Sh SEE ALSO
.Xr mdoctree 1 ,
.Xr mdoclint 1 ,
.Xr mdoc.samples 7 ,
.Xr mdoc 7 ,
.Xr mdoc 3
.\" 
.Sh AUTHORS
The
.Nm
utility was written by 
.An Kristaps Dzonsons Aq kristaps@kth.se .
.\" SECTION
.Sh CAVEATS
See
.Xr mdoc 3
for a list of bugs, caveats, and incomplete macros regarding the
document parse.
.Pp
The 
.Nm
utility doesn't yet know how to display the following:
.Pp
.Bl -bullet -compact
.It
The \-hang and \-column
.Sq \&Bl
lists are not yet supported.
.It
The \-literal and \-unfilled 
.Sq \&Bd
displays only accept text contents.
.It
The
.Sq \&Xo/Xc
pair isn't supported (and never will be).
.El
