.\" $Id$
.\"
.\" Copyright (c) 2009 Kristaps Dzonsons <kristaps@kth.se>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the
.\" above copyright notice and this permission notice appear in all
.\" copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
.\" PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt mdoclint 1
.Os
.\" SECTION
.Sh NAME
.Nm mdoclint
.Nd mdoc macro compiler
.\" SECTION
.Sh SYNOPSIS
.Nm mdoclint
.Op Fl vV
.Op Fl f Ns Ar options...
.Op Fl W Ns Ar err...
.Op Ar infile
.\" SECTION
.Sh DESCRIPTION
The
.Nm
utility parses a BSD 
.Dq mdoc 
manual pages and validates its syntax tree.  The arguments are as
follows:
.Bl -tag -width XXXXXXXXXXXX -offset XXXX
.\" ITEM
.It Fl v
Print verbose parsing output.
.\" ITEM
.It Fl V
Print version and exit.
.\" ITEM
.It Fl f Ns Ar option...
Override default compiler behaviour.  See 
.Sx Compiler Options
for details.
.\" ITEM
.It Fl W Ns Ar err...
Print warning messages.  May be set to 
.Fl W Ns Ar all
for all warnings, 
.Ar compat
for groff/troff-compatibility warnings, or
.Ar syntax
for syntax warnings.  If
.Fl W Ns Ar error 
is specified, warnings are considered errors and cause utility
termination.  Multiple 
.Fl W
arguments may be comma-separated, such as
.Fl W Ns Ar error,all .
.\" ITEM
.It Ar infile
Read input from
.Ar infile ,
which may be 
.Dq \-
for stdin.
.El
.\" PARAGRAPH
.Pp
The
.Nm
utility is a front-end for
.Xr mdoc 3 ,
which parses the 
.Dq mdoc
input, documented at
.Xr mdoc 7
and
.Xr mdoc.samples 7 ,
into an abstract syntax tree.  By default, it reads from stdin.
.\" PARAGRAPH
.Pp
.Ex -std mdoclint
.\" SUB-SECTION
.Ss Compiler Options
Default compiler behaviour may be overriden with the
.Fl f
flag.  The available options are as follows:
.Bl -tag -width XXXXXXXXXXXX -offset XXXX
.It Fl f Ns Ar ign-scope
When rewinding the scope of a block macro, forces the compiler to ignore
scope violations.  This can seriously mangle the resulting tree.
.It Fl f Ns Ar ign-escape
Ignore invalid escape sequences.
.It Fl f Ns Ar ign-macro
Ignore unknown macros at the start of input lines.
.El
.\" PARAGRAPH
.Pp
As with the
.Fl W
flag, multiple
.Fl f
options may be grouped and delimited with a comma.  Using
.Fl f Ns Ar ign-scope,ign-escape ,
for example, will try to ignore scope and character-escape errors.
.\" SUB-SECTION
.Ss Input Encoding
The
.Nm
utility expects its input to be 7-bit ASCII as defined in
.Xr ascii 7 .
The only non-graphing characters accepted are spaces,
.Sq \  ,
and tabs,
.Sq \et .
Tabs are only accepted in literal block-displays and as column
delimiters.
.Pp
Only Unix-style newlines (\en) are accepted; if the newline is escaped,
the line is concatenated with the next.
.\" SECTION
.Sh EXAMPLES
To validate this manual page:
.\" PARAGRAPH
.Pp
.D1 % mdoclint \-Wall,error mdoclint.1 
.\" SECTION
.Sh SEE ALSO
.Xr mdocterm 1 ,
.Xr mdoctree 1 ,
.Xr mdoc.samples 7 ,
.Xr mdoc 7 ,
.Xr mdoc 3
.\" 
.Sh AUTHORS
The
.Nm
utility was written by 
.An Kristaps Dzonsons Aq kristaps@kth.se .
.\" SECTION
.Sh CAVEATS
See
.Xr mdoc 3
for a list of bugs, caveats, and incomplete macros.
