# $OpenBSD: Makefile,v 1.1 2023/10/24 20:30:49 schwarze Exp $

# disable for now because groff changed the global indentation
#REGRESS_TARGETS	 = basic
LINT_TARGETS	 = basic

.include <bsd.regress.mk>
